services:
  db:
    image: postgres:16
    container_name: avisclient_postgres
    restart: always
    environment:
      POSTGRES_USER: tanteli
      POSTGRES_PASSWORD: tanteli123
      POSTGRES_DB: avisdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avisclient_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://tanteli:tanteli123@db:5432/avisdb

volumes:
  postgres_data:
